# Copyright 2011-2014 Rice University. Licensed under the Affero General Public
# License version 3 or later.  See the COPYRIGHT file for details.
sudo: false
language: ruby
rvm: 2.6.1
cache: bundler
bundler_args: --without production --retry=6
addons:
  postgresql: 9.6
services: redis-server
script: bundle exec parallel_rspec ./spec
branches:
  only:
    - master
before_script:
  - export OXE_DB_USER=postgres
  - export OXE_DB_PASS=
  - export OXE_TEST_DB=travis_ci_test
  - export PARALLEL_TEST_PROCESSORS=2
  - bundle exec rake --trace parallel:create parallel:load_schema parallel:seed
before_install:
  - gem install bundler:2.0.1
